# -*- coding: utf-8 -*-
"""think-week4-108060016-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vplsa2wqdRLz4h_Ev-oIIBVFrL-Ft1O2
"""

1 print("hello world")

print("hello world")

print("你好嗎??")

print("into the unknown")
print("into the unknown")
print("into the unknown~~~")

"""哈囉囉"""



"""阿囉哈~~~~"""

