# -*- coding: utf-8 -*-
"""think-week4-A108060016-3(2).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KOKtWunvjgSyWZqSjhzs79UHFuyO2wAD
"""

print("Hello World")

print("你好嗎")

print("Hello World")
print("你好嗎")



"""早安

拉拉拉~
"""



"""看的到嗎?"""



"""看得到~yaaaaaaa~"""

