# -*- coding: utf-8 -*-
"""W4-108060016-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M6NBrf2E7RwnsZkwL3Ab52G6sAs_1r_R
"""

print("Hello World")

print("你好嗎")

print("Hello World")
print("你好嗎")

